### ISSUE TITLE
Broken Links "Validating the Model" get_predictions() and conf_int()

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-sarima-models-lab#1]
In the section "Validating the Model" the get_predictions() and conf_int() links are broken/ 404 error.

This: 

The get_prediction() and conf_int() attributes allow us to obtain the values and associated confidence intervals for forecasts of the time series.

Documentation of get_predictions()

Documentation for conf_int()

**Comment by hoffm386** [comment]
I'm not sure what went wrong here but I'm seeing working links:

[Documentation for `get_prediction()`](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.get_prediction.html)

[Documentation for `conf_int()`](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.conf_int.html)

Closing this one out
