### ISSUE TITLE
Data does not load correctly

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-sarima-models-lab#2]
I had a problem with this dataset earlier and in this lab the dates appear with as: b'yyyy-mm-dd'.  When I use the answer from the answer key there is an error and I can not proceed with the lab.  I brought this to my instructors attention, but we were not able to fix it.

**Comment by jessepisel** [comment]
This was addressed by commit 5d3a0b88ea724a5fe3bfe37abf190163321f4e64. I am closing this issue at this time.
